services:
  artesanias-inventory-service:
    image: brayan22/artesanias-inventory-service:latest
    environment:
      - CONFIG_SERVER_URL=http://artesanias-config-server:9196
      - JDBC_DATABASE_URL=jdbc:postgresql://${RDS_URL}:5432/postgres
      - JDBC_DATABASE_USERNAME=${DB_USERNAME}
      - JDBC_DATABASE_PASSWORD=${DB_PASSWORD}
      - INVENTORY_SERVICE_PORT=9090
      - HOST=https://restauranteapirest.brayandev.info
      - EUREKA_URI=http://artesanias-discovery-server:8761/eureka/
      - HOSTNAME=artesanias-inventory-service
    hostname: artesanias-inventory-service
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  backend:
    external: true